.\" Manpage for gitshell.
.\" Contact horne@ncf.ca to correct errors or typos.
.TH GITSH-EXIT 1 "21 February 2014" "0.1" "GitSHell Manual"
.SH NAME
gitsh-exit \- exit GitSHell
.SH SYNOPSIS
[gitsh] exit
.SH DESCRIPTION
\fIgitsh\fR \fIexit\fR is a GitSHell command which exits the command shell.
.SH OPTIONS
None
.SH EXAMPLES
None
.SH BUGS
No known bugs.
.SH AUTHOR
Gregory D. Horne (horne at ncf dot ca)
.SH GITSH
An internal gitsh(1) command; not callable from a standard Unix shell.
