.\" Manpage for gitshell.
.\" Contact horne@ncf.ca to correct errors or typos.
.TH GITSH-CREATE 1 "21 February 2014" "0.1" "GitSHell Manual"
.SH NAME
gitsh-create \- create a local repository, and optionally a corresponding remote repository
.SH SYNOPSIS
[gitsh] create <repository_type> <repository_name>
.SH DESCRIPTION
.nh
.ad l
\fIgitsh\fR \fIcreate\fR is a GitSHell command which create a local repository, and optionally a
corresponding remote repository if requested.
.fi
.PP
.nh
.ad l
<repository_type> is either 'local' or 'remote'. If <repository_type> is local,
then <repository_name> is created under the repository base defined in the
configuration file. If <repository_type> is remote, then <repository_name> is
created as a GitHub hosted repository and locally under the repository base defined in
the configuration file.
.PP
<repository name> is assumed to contain no space characters in its name;
this is not validated.
.fi
.PP
If the repository type or name is missing, then an error message
is displayed. There is no default repository type.
.SH OPTIONS
None
.SH EXAMPLES
.PP
To verify successful creation of the local repository open the repository.
.PP
.nf
gitsh:[]> create local sample
gitsh:[]> open sample
gitsh:[sample]> 
.fi
.PP
To verify successful creation of the remote repository visit  
https://github.com/users/<repository_name>.
.PP 
.nf
gitsh:[]> create remote sample
gitsh:[]> open sample
gitsh:[sample]>
.fi
.SH BUGS
No known bugs.
.SH AUTHOR
Gregory D. Horne (horne at ncf dot ca)
.SH GITSH
An internal gitsh(1) command; not callable from a standard Unix shell.
